name: Auto Build APK

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - 'simple_live_app/**'
      - '.github/workflows/auto_build_apk.yml'
  pull_request:
    branches:
      - 'main'
      - 'master'
    paths:
      - 'simple_live_app/**'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      # 签出代码
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 设置Java环境
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      
      # 设置Flutter环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true
      
      # 更新Flutter packages
      - name: Install dependencies
        run: |
          cd simple_live_app
          flutter pub get
      
      # 构建APK
      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release --split-per-abi
      
      # 上传APK到Artifacts
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
      
      # 如果是标签推送，创建Release
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
          prerelease: true