name: Quick APK Build

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches:
      - 'dev'
    paths:
      - 'simple_live_app/**'
      - '.github/workflows/quick_apk_build.yml'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      # 签出代码
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 设置Java环境
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      
      # 设置Flutter环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true
      
      # 更新Flutter packages
      - name: Install dependencies
        run: |
          cd simple_live_app
          flutter pub get
      
      # 构建APK (仅构建arm64-v8a架构以加快构建速度)
      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release --target-platform android-arm64
      
      # 上传APK到Artifacts
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-live-app-arm64.apk
          path: simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk