name: Signed APK Build

on:
  workflow_dispatch: # 允许手动触发
  push:
    tags:
      - "v*"

jobs:
  build-signed-apk:
    runs-on: ubuntu-latest
    
    steps:
      # 签出代码
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 设置Java环境
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      
      # 设置Flutter环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true
      
      # 下载签名密钥
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
          
      # 创建key.properties文件
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.decode_keystore.outputs.filePath }}" > simple_live_app/android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> simple_live_app/android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> simple_live_app/android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> simple_live_app/android/key.properties
      
      # 更新Flutter packages
      - name: Install dependencies
        run: |
          cd simple_live_app
          flutter pub get
      
      # 构建签名APK
      - name: Build Signed APK
        run: |
          cd simple_live_app
          flutter build apk --release --split-per-abi
      
      # 上传签名APK到Artifacts
      - name: Upload Signed APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-apks
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
      
      # 创建Release并上传APK
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
          prerelease: false